name: Deploy to staging env
on:
  push:
    branches: [ stage ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/tcode-ops-stage
          docker pull mrsmith9ja/tcode-parse-api
          docker-compose down
          docker-compose up -d