name: Deploy to staging env
on:
  workflow_run:
    branches: [ develop ]
    workflows: ["Docker Image CI"]
    types:
      - completed
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy...
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/tcode-ops-stage
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/tcode-parse-api
          docker-compose down
          docker-compose up -d
    - name: Send slack message
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployed API to staging ENV"}' ${{ secrets.SLACK_API }}
