name: Docker Image CI

on:
  push:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo ${{secrets.DOCKER_HUB_ACCESS_TOKEN}} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/tcode-parse-api:latest
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/tcode-parse-api:$(date +%s)
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/tcode-parse-api:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/tcode-parse-api
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployed Image to Docker registry"}' ${{ secrets.SLACK_API }}
